---
domains:
  canonical:
    - next.erp.{{ DOMAIN_PRIMARY }}
csp:
  whitelist:
    connect-src:
      - "{{ lookup('domain', 'web-app-erpnext') }}"
      - "wss://{{ lookup('domain', 'web-app-erpnext') }}"
  flags:
    script-src:
      unsafe-eval: true
    script-src-elem:
      unsafe-inline: true
      unsafe-eval: true
    style-src-attr:
      unsafe-inline: true
networks:
  local:
    subnet: 192.168.214.0/24
