---
sites:
  type: volume
  name: erpnext_sites
  mounts:
    - service: erpnext-configurator
      target: /home/frappe/frappe-bench/sites
    - service: erpnext-backend
      target: /home/frappe/frappe-bench/sites
    - service: erpnext-websocket
      target: /home/frappe/frappe-bench/sites
    - service: erpnext-scheduler
      target: /home/frappe/frappe-bench/sites
    - service: erpnext-queue-short
      target: /home/frappe/frappe-bench/sites
    - service: erpnext-queue-long
      target: /home/frappe/frappe-bench/sites
    - service: erpnext-frontend
      target: /home/frappe/frappe-bench/sites
logs:
  type: volume
  name: erpnext_logs
  mounts:
    - service: erpnext-configurator
      target: /home/frappe/frappe-bench/logs
    - service: erpnext-backend
      target: /home/frappe/frappe-bench/logs
    - service: erpnext-websocket
      target: /home/frappe/frappe-bench/logs
    - service: erpnext-scheduler
      target: /home/frappe/frappe-bench/logs
    - service: erpnext-queue-short
      target: /home/frappe/frappe-bench/logs
    - service: erpnext-queue-long
      target: /home/frappe/frappe-bench/logs
    - service: erpnext-frontend
      target: /home/frappe/frappe-bench/logs
