---
# nocheck: info-media no official demo video
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Containerized icon server for hosting the Simple Icons brand SVG and PNG collection for web and documentation use
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - docker
    - icons
    - branding
    - svg
    - png
  issue_tracker_url: https://s.infinito.nexus/issues
