---
# nocheck: info-media no official demo video
galaxy_info:
  author: Marko Pjevac, Kevin Veen-Birkenbach
  description: Documentation generator that builds HTML from a source repository and serves it through a lightweight HTTP server
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - documentation
    - sphinx
    - docker
    - automation
    - deployment
  issue_tracker_url: https://s.infinito.nexus/issues
