---
csp:
  flags:
    style-src-attr:
      unsafe-inline: true
    script-src-elem:
      unsafe-inline: true
  whitelist:
    font-src:
      - "data:"
domains:
  canonical:
    - pgadmin.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.49.0/24
