---
enabled: "{{ lookup('config', 'web-app-mattermost', 'services.gitlab.enabled') | bool }}"
required: false
mechanism: plugin
source: upstream
version: "v2.2.0"
bridges:
  - gitlab
update:
  monitored: true
  catalog: github-releases
  upstream_id: mattermost/mattermost-plugin-gitlab
config:
  plugin_id: com.github.manland.mattermost-plugin-gitlab
  partner_url: "{{ lookup('tls', 'web-app-gitlab', 'url.base') }}"
