---
- services:
    tor:
      enabled: true
    openldap:
      exposed: true  # nocheck: variants-static-override
- services:
    tor:
      enabled: false
      shared: false  # nocheck: variants-static-override
