---
# It is necessary to shut the projects down, when reset is activated. 
# Otherwise it can lead to this bug:
# https://github.com/ansible/ansible/issues/10244
- name: "📦 Install '{{ COMPOSE_DOWN_ALL_PACKAGE }}' system-wide via pip"
  include_role:
    name: sys-pip-install
  vars:
    # TODO: switch to the PyPI name 'docodol' once it is published
    package_name: "git+{{ COMPOSE_DOWN_ALL_REPO }}@{{ COMPOSE_DOWN_ALL_REF }}"
    global_install: true

- name: "🧹 Shutdown compose instances in '{{ DIR_COMPOSITIONS }}'"
  command: "{{ COMPOSE_DOWN_ALL_PACKAGE }} {{ DIR_COMPOSITIONS }}"

- name: "🗑️ Remove directory '{{ DIR_COMPOSITIONS }}' and all its contents"
  file:
    path: "{{ DIR_COMPOSITIONS }}"
    state: absent
