"""Lint guard: every ``roles/<role>/README.md`` MUST conform to the
role README convention defined in
``docs/contributing/artefact/files/role/readme_md.md``.

A committed role README holds only the prose a human writes. The Cosmos
diagram, the Quick Setup block and the Credits block are derived from role
metadata and are written into the scratch checkout by the documentation
build, so they MUST NOT be committed.

Enforced (hard fail) rules
==========================

1. **No emojis in any heading.** Galaxy / dashboard tooling parses heading
   text; emojis break the parser. The convention forbids emojis in role
   README headings at every level.
2. **Required H2 sections present.** The mandatory sections are the H2s
   ``templates/roles/README.md.j2.tmpl`` emits with no optional context,
   minus the generated ones: ``## Description``, ``## Overview`` and
   ``## Features``. The template is the single source of truth;
   ``cli.build.docs.readme.schema`` reads it.
3. **Section order.** Those required H2s MUST appear in the template order
   (extra H2s MAY be interleaved between them).
4. **No generated sections.** ``## Cosmos``, ``## Quick Setup`` and
   ``## Credits`` are produced by the documentation build from
   ``meta/services.yml``, ``categories.yml`` and ``galaxy_info.author``.
   A committed copy goes stale silently, so it is a hard fail.

Soft / fuzzy rules from ``readme_md.md`` (sentence-case headings,
"H1 must be the human-readable software name", "Description must link the
software to its official website on first use", "every Feature item starts
with a bold label and a colon") are deliberately NOT enforced here — they
need human judgement and would produce false positives.

Files outside ``roles/<role>/README.md`` (for example
``roles/<role>/files/README.md``) are out of scope. Presence of the
top-level role README is enforced separately by
``tests/integration/roles/applications/test_web_app_readme.py``.
"""

from __future__ import annotations

import re
import unittest
from typing import TYPE_CHECKING

from cli.build.docs.readme import schema
from cli.build.docs.readme.generate import MANAGED_SECTIONS
from utils.cache.files import PROJECT_ROOT, read_text

if TYPE_CHECKING:
    from pathlib import Path

ROLES_DIR = PROJECT_ROOT / "roles"

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$", re.MULTILINE)
_EMOJI_RE = re.compile(
    "[\U00002600-\U000027bf\U0001f000-\U0001f2ff\U0001f300-\U0001faff]"
)

_REQUIRED_SECTIONS: tuple[str, ...] = tuple(
    title for title in schema.required_sections() if title not in MANAGED_SECTIONS
)


def _role_readmes() -> list[Path]:
    if not ROLES_DIR.is_dir():
        return []
    return sorted(
        role_dir / "README.md"
        for role_dir in ROLES_DIR.iterdir()
        if role_dir.is_dir() and (role_dir / "README.md").is_file()
    )


def _parse_headings(text: str) -> list[tuple[int, int, str]]:
    """Return [(line_no, level, title)] for every heading in `text`."""
    out: list[tuple[int, int, str]] = []
    for ln, line in enumerate(text.splitlines(), 1):
        match = _HEADING_RE.match(line)
        if match:
            out.append((ln, len(match.group(1)), match.group(2).strip()))
    return out


def _validate_readme(path: Path) -> list[str]:
    """Return human-readable problems for one role README."""
    try:
        text = read_text(str(path))
    except (OSError, UnicodeDecodeError) as exc:
        return [f"read error: {exc}"]

    problems: list[str] = []
    headings = _parse_headings(text)

    for ln, _level, title in headings:
        if _EMOJI_RE.search(title):
            problems.append(f"L{ln}: heading contains emoji: {title!r}")

    h2_titles = [title for _, level, title in headings if level == 2]
    h2_set = set(h2_titles)
    problems.extend(
        f"missing required H2 section '{required}'"
        for required in _REQUIRED_SECTIONS
        if required not in h2_set
    )

    problems.extend(
        f"'## {generated}' is generated by the documentation build from role "
        f"metadata and MUST NOT be committed; delete the section"
        for generated in MANAGED_SECTIONS
        if generated in h2_set
    )

    present_required = [t for t in h2_titles if t in set(_REQUIRED_SECTIONS)]
    expected_order = [r for r in _REQUIRED_SECTIONS if r in h2_set]
    if present_required != expected_order:
        problems.append(
            "required sections out of order; they MUST appear in the template "
            f"order: {' → '.join(_REQUIRED_SECTIONS)} "
            "(extra sections MAY be interleaved between them)"
        )

    return problems


class TestRoleReadme(unittest.TestCase):
    """Every role README MUST conform to the readme_md.md role convention."""

    def test_role_readmes_are_conformant(self) -> None:
        offenders: dict[Path, list[str]] = {}
        for path in _role_readmes():
            problems = _validate_readme(path)
            if problems:
                offenders[path] = problems

        if not offenders:
            return

        lines = [
            (
                f"{len(offenders)} role README.md file(s) violate "
                f"docs/contributing/artefact/files/role/readme_md.md:"
            )
        ]
        for path, problems in sorted(offenders.items()):
            lines.append(f"  - {path.relative_to(PROJECT_ROOT)}:")
            lines.extend(f"      * {problem}" for problem in problems)

        self.fail("\n".join(lines))


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
