---
- include_tasks: utils/once/flag.yml

- name: 📂 Include mail dependency (queued to post-load during preload)
  include_role:
    name: sys-service-loader
    tasks_from: list_or_shoot.yml
  vars:
    list_or_shoot_roles:
      - sys-svc-mail
  when: not (run_once_sys_svc_mail | default(false) | bool)

- include_role:
    name: sys-service
  vars:
    system_service_tpl_on_failure: "{{ lookup('unit_name','sys-ctl-alm-telegram@', suffix=False) }}%i.service"
