---
- name: "✅ ensure MDAD inventory host_vars dir exists"
  ansible.builtin.file:
    path: "{{ MATRIX_MDAD_DIR }}/inventory/host_vars/{{ MATRIX_SYNAPSE_DOMAIN }}"
    state: directory
    mode: "0755"

- name: "📄 render MDAD inventory hosts file"
  stack_host_template:
    src: "flavor/ansible/hosts.j2"
    dest: "{{ MATRIX_MDAD_DIR }}/inventory/hosts"
    mode: "0644"

- name: "📄 render MDAD host_vars vars.yml"
  stack_host_template:
    src: "flavor/ansible/vars.yml.j2"
    dest: "{{ MATRIX_MDAD_DIR }}/inventory/host_vars/{{ MATRIX_SYNAPSE_DOMAIN }}/vars.yml"
    mode: "0644"
