---
gnome-extensions:
  modes:
    host:
      enabled: true
  repository: https://github.com/kevinveenbirkenbach/cli-gnome-extension-manager.git
  ref: v1.0.0
  plugins: []
  lifecycle: pre-alpha
  min_storage: "50MB"
  cpus: "0.1"
  mem_reservation: "32m"
  mem_limit: "64m"
  pids_limit: 64
