---
application_id: svc-docker-registry
entity_name: "{{ application_id | get_entity_name }}"

service_is_stateful: true

REGISTRY_IMAGE: "{{ lookup('config', application_id, 'services.registry.image') }}"
REGISTRY_VERSION: "{{ lookup('config', application_id, 'services.registry.version') }}"
REGISTRY_CONTAINER: "{{ lookup('config', application_id, 'services.registry.name') }}"
REGISTRY_PORT: "{{ lookup('config', application_id, 'services.registry.ports.local.registry') }}"
REGISTRY_DATA_VOLUME: "{{ lookup('config', application_id, 'volumes.data.name') }}"
