---
application_id: "svc-ai-ollama"
entity_name: "{{ application_id | get_entity_name }}"

OLLAMA_CONTAINER: "{{ lookup('config', application_id, 'services.ollama.name') }}"
OLLAMA_PORT: "{{ lookup('config', application_id, 'services.ollama.ports.internal.http') }}"
OLLAMA_PRELOAD_MODELS: "{{ lookup('config', application_id, 'services.ollama.preload_models') }}"
