FROM {{ NEXTCLOUD_IMAGE }}:{{ NEXTCLOUD_VERSION }}
{% if NEXTCLOUD_ONLYOFFICE_ENABLED | bool %}
RUN apk add --no-cache ca-certificates && update-ca-certificates
{% endif %}

COPY {{ NEXTCLOUD_INIT_GATE_FILE }} /usr/local/bin/{{ NEXTCLOUD_INIT_GATE_FILE }}
RUN chmod 0755 /usr/local/bin/{{ NEXTCLOUD_INIT_GATE_FILE }}
ENTRYPOINT ["/usr/local/bin/{{ NEXTCLOUD_INIT_GATE_FILE }}"]
CMD ["php-fpm"]
