---
RESOURCE_HOST_CPUS_OVERRIDE: # Set to an integer in the inventory to pin the CPU count instead of measuring it
RESOURCE_HOST_MEM_MB_OVERRIDE: # Set to MiB in the inventory to pin the memory instead of measuring it

RESOURCE_HOST_CPUS: "{{ lookup('resource', 'host_cpus') }}"

RESOURCE_CPUS: "{{ lookup('resource', 'cpus') }}"
RESOURCE_MEM_RESERVATION: "{{ lookup('resource', 'mem_reservation') }}"
RESOURCE_MEM_LIMIT: "{{ lookup('resource', 'mem_limit') }}"
RESOURCE_PIDS_LIMIT: "{{ lookup('resource', 'pids_limit') }}"

POSTGRES_MAX_CONNECTIONS: "{{ lookup('resource', 'postgres_max_connections') }}"
POSTGRES_ALLOWED_AVG_CONNECTIONS: "{{ lookup('resource', 'postgres_allowed_avg_connections') }}"
POSTGRES_SUPERUSER_RESERVED_CONNECTIONS: "{{ lookup('resource', 'postgres_superuser_reserved_connections') }}"
POSTGRES_SHARED_BUFFERS: "{{ lookup('resource', 'postgres_shared_buffers') }}"
POSTGRES_WORK_MEM: "{{ lookup('resource', 'postgres_work_mem') }}"
POSTGRES_MAINTENANCE_WORK_MEM: "{{ lookup('resource', 'postgres_maintenance_work_mem') }}"
POSTGRES_MAX_LOCKS_PER_TRANSACTION: "{{ lookup('resource', 'postgres_max_locks_per_transaction') }}"
POSTGRES_DELAY: "{{ lookup('resource', 'postgres_delay') }}"

TIMEOUT_FACTOR: 1
