FROM taigaio/taiga-back:{{ TAIGA_VERSION }}

{% if TAIGA_OIDC_ENABLED | bool %}
RUN rm -rf /var/lib/apt/lists/* && \
    apt-get -o Acquire::Retries=3 update && \
    apt-get -o Acquire::Retries=3 install -y --no-install-recommends git && \
    pip install --no-cache-dir {{ TAIGA_PLUGIN_PIP_INSTALL_ARGS }} && \
    apt-get purge -y --auto-remove git && \
    rm -rf /var/lib/apt/lists/*
{% else %}
RUN pip install --no-cache-dir {{ TAIGA_PLUGIN_PIP_INSTALL_ARGS }}
{% endif %}
