---
jellyfin_config:
  type: volume
  mounts:
    - service: jellyfin
      target: /config
jellyfin_cache:
  type: volume
  mounts:
    - service: jellyfin
      target: /cache
jellyfin_media:
  type: volume
  mounts:
    - service: jellyfin
      target: /media
