---
_compose_ca_applicable: >-
  {{ (lookup('domains') | has_domain(application_id))
     and (lookup('tls', application_id, 'enabled') | bool)
     and (lookup('tls', application_id, 'mode') == 'self_signed') }}
