---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Self-hosted platform for file sync, sharing, and collaboration with Keycloak SSO and central LDAP directory
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - opencloud
    - docker
    - oidc
    - ldap
    - cloud
    - files
    - collaboration
    - web
  issue_tracker_url: https://s.infinito.nexus/issues
