---
data:
  type: volume
  name: opencloud_data
  mounts:
    - service: application
      target: /var/lib/opencloud

config:
  type: volume
  name: opencloud_config
  mounts:
    - service: application
      target: /etc/opencloud
