---
- include_tasks: 01_core.yml
  when: run_once_svc_prx_openresty is not defined

- name: "🎛️ Reinitialize OpenResty Handler"
  include_tasks: utils/load/handlers.yml
  vars:
    handler_role_name: "svc-prx-openresty"
