---
application_id: svc-db-postgres
entity_name: "{{ application_id | get_entity_name }}"

database_type: "{{ entity_name }}"

POSTGRES_CONTAINER: "{{ lookup('config', application_id, 'services.' ~ entity_name ~ '.name') }}"
POSTGRES_CONTAINER_ADDRESS: "{{ lookup('container_address', application_id, entity_name) }}"
POSTGRES_IMAGE: "{{ lookup('config', application_id, 'services.' ~ entity_name ~ '.image') }}"
POSTGRES_VERSION: "{{ lookup('config', application_id, 'services.' ~ entity_name ~ '.version') }}"
POSTGRES_VERSION_MAJOR: "{{ POSTGRES_VERSION | regex_replace('^([0-9]+).*', '\\1') }}"
POSTGRES_PASSWORD: "{{ lookup('config', application_id, 'credentials.POSTGRES_PASSWORD') }}"
POSTGRES_PORT: "{{ database_port | default(lookup('config', application_id, 'services.postgres.ports.local.postgres')) }}"
POSTGRES_EXPOSE_LOCAL: true
POSTGRES_LOCAL_HOST: "127.0.0.1"
POSTGRES_LIBRARIES: "{{ lookup('postgres_libraries', lookup('service_extensions', 'postgres').values() | sum(start=[]) | unique | list) }}"
POSTGRES_RETRIES: 5
