---
application_id: "web-app-mastodon"
entity_name: "{{ application_id | get_entity_name }}"

MASTODON_CONTAINER: "{{ lookup('config', application_id, 'services.mastodon.name') }}"
MASTODON_CONTAINER_ADDRESS: "{{ lookup('container_address', application_id, entity_name) }}"
MASTODON_SERVICE_NAME: "mastodon"

MASTODON_STREAMING_CONTAINER: "{{ lookup('config', application_id, 'services.streaming.name') }}"
MASTODON_STREAMING_SERVICE_NAME: "streaming"

MASTODON_SIDEKIQ_CONTAINER: "{{ lookup('config', application_id, 'services.mastodon.name') }}-sidekiq"
MASTODON_SIDEKIQ_SERVICE_NAME: "sidekiq"

MASTODON_ALLOWED_PRIVATE_ADDRESSES: "{{ lookup('config', 'svc-db-postgres', 'server.networks.local.subnet') if 'web-app-chess' in group_names else ''}}"
MASTODON_OIDC_ENABLED: "{{ lookup('config', application_id, 'services.sso.enabled')  }}"

MASTODON_HTTP_ONLY_ENABLED: "{{ not (lookup('tls', application_id, 'enabled') | bool) }}"
MASTODON_OVERRIDES_DIR: "{{ lookup('container', application_id, 'directories.instance') }}/overrides"
MASTODON_FORCE_SSL_OVERRIDE_FILE: "{{ MASTODON_OVERRIDES_DIR }}/zzz_disable_force_ssl.rb"
