---
# nocheck: info-media In-house Infinito.Nexus tool (Meta Infinite Graph) written by the same author; only a GitHub repo exists, no third-party vendor product homepage or official demo video.
logo:
  class: fa-solid fa-brain
