---
# General
application_id: "web-app-lam"

LAM_CONTAINER: "{{ application_id | get_entity_name }}"
LAM_PASSWORD: "{{ lookup('config', application_id, 'secrets.credentials.administrator_password') }}"
