---
application_id: web-svc-onlyoffice
domain: "{{ lookup('domain',application_id) }}"
http_port: "{{ lookup('config', application_id, 'services.onlyoffice.ports.local.http') }}"
container_port: 80
entity_name: "{{ application_id | get_entity_name }}"

ONLYOFFICE_CONTAINER: "{{ lookup('config', application_id, 'services.' ~ entity_name ~ '.name') }}"
ONLYOFFICE_JWT_SECRET: "{{ lookup('config', application_id, 'credentials.onlyoffice_jwt_secret') }}"
