---
- name: "📌 WP OIDC: write the settings to every site of the network"
  when: IS_STACK_HOST | bool
  ansible.builtin.shell:
    cmd: >
      container exec -i --user {{ WORDPRESS_USER | quote }}
      -e {{ ('WP_OIDC_SETTINGS=' ~ (lookup('config', application_id, 'addons.daggerhart-openid-connect-generic.config.oidc_settings') | to_json | b64encode)) | quote
      }}
      {{ WORDPRESS_CONTAINER_ADDRESS }}
      wp eval-file - --path={{ WORDPRESS_DOCKER_HTML_PATH | quote }}
    stdin: "{{ lookup('file', 'php/oidc/settings.php') }}"
  changed_when: true
  no_log: "{{ MASK_CREDENTIALS_IN_LOGS | bool }}"
