---
# include-gated: when: DEPLOYMENT_MODE == "compose"
- name: 🐳 compose pull
  command:
    cmd: "compose pull"
    chdir: "{{ lookup('container', application_id, 'directories.instance') }}"
  timeout: "{{ lookup('timeout', 3600) | int }}"

- name: 🐳 compose up
  command:
    cmd: "compose up -d --remove-orphans"
    chdir: "{{ lookup('container', application_id, 'directories.instance') }}"
  register: result
  until: result is succeeded
  timeout: "{{ lookup('timeout', 1800) | int }}"
  retries: 12
  delay: 30
