[Unit]
StartLimitIntervalSec=300
StartLimitBurst=3

[Service]
Restart=on-failure
RestartSec=2
Environment="OPTIONS=-L SYSLOG -f /etc/ganesha/ganesha.conf -N NIV_EVENT"
ExecStartPost=/usr/bin/timeout 20 /bin/bash -c 'until (exec 3<>/dev/tcp/127.0.0.1/2049) 2>/dev/null; do sleep 1; done'
TimeoutStopSec=10
TimeoutAbortSec=10
