---
- name: "📦 Connect '{{ DISCOURSE_CONTAINER }}' to network '{{ DISCOURSE_PG_NETWORK }}'"
  command: >
    container network connect {{ DISCOURSE_PG_NETWORK }} {{ DISCOURSE_CONTAINER }}
  register: network_connect
  failed_when: >
    network_connect.rc != 0 and
    not (network_connect.stderr | default('') | docker_network_noop('connect'))
  changed_when: network_connect.rc == 0

- name: "🧹 Remove {{ DISCOURSE_NETWORK }} from DB container {{ application_id }}"
  command: >
    container network disconnect {{ DISCOURSE_NETWORK }} {{ lookup('database', application_id, 'container') }}
  register: network_disconnect
  failed_when: >
    network_disconnect.rc != 0 and
    not (network_disconnect.stderr | default('') | docker_network_noop('disconnect'))
  changed_when: network_disconnect.rc == 0
