#!/usr/bin/env bash
# Runs in-node on the backup host. Installs the pull identity so the
# deployed svc-bkp-remote-2-local unit can reach backup@<provider> over
# the user-backup ssh wrapper.
#
# Arguments: none.
# Stdin: the backup ssh private key (generated by write_extras).
set -euo pipefail

mkdir -p /root/.ssh
chmod 700 /root/.ssh
cat >/root/.ssh/id_ed25519
chmod 600 /root/.ssh/id_ed25519
printf 'Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n' >/root/.ssh/config
chmod 600 /root/.ssh/config
