---
- name: "🧩 load docker, db and proxy for {{ application_id }}"
  include_role:
    name: sys-stk-full

- name: "📄 Render ejabberd configuration"
  stack_host_template:
    src: configuration.yml.j2
    dest: "{{ XMPP_CONFIG_FILE }}"
    mode: "0644"
  notify:
    - compose-up
