---
- include_tasks: utils/once/flag.yml

- name: "🧩 load front-proxy + dev-git for {{ application_id }}"
  include_role:
    name: "{{ dependency_role }}"
  loop:
    - sys-stk-front-proxy
    - dev-git
  loop_control:
    loop_var: dependency_role
