---
enabled: "{{ lookup('api_enabled', 'jira') }}"
required: true
mechanism: plugin
source: upstream
config:
  plugin_configuration:
    - appid: "integration_jira"
      configkey: "client_id"
      configvalue: "{{ lookup('api', 'jira.client_id') }}"
    - appid: "integration_jira"
      configkey: "client_secret"
      configvalue: "{{ lookup('api', 'jira.client_secret') }}"
