---
enabled: "{{ lookup('api_enabled', 'github') }}"
required: true
mechanism: plugin
source: upstream
config:
  plugin_configuration:
    - appid: "integration_github"
      configkey: "client_id"
      configvalue: "{{ lookup('api', 'github.client_id') }}"
    - appid: "integration_github"
      configkey: "client_secret"
      configvalue: "{{ lookup('api', 'github.client_secret') }}"
