---
enabled: "{{ lookup('config', 'web-app-openproject', 'services.nextcloud.enabled') | bool }}"
required: false
mechanism: module
source: bundled
bridges:
  - nextcloud
config:
  provider_type: nextcloud
  admin_path: /admin/settings/storages
