---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: The Docker RabbitMQ Role offers an easy and efficient way to run a central RabbitMQ message broker inside a Docker container, with per-consumer
    vhost and user isolation, making it ideal for production or local development.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - rabbitmq
    - docker
    - queue
    - administration
    - central-database
  issue_tracker_url: https://s.infinito.nexus/issues
