---
- name: 📂 Include install routines
  include_tasks: "{{ joomla_step }}"
  loop:
    - 03_install.yml
    - 04_debug.yml
    - 05_patch.yml
  loop_control:
    loop_var: joomla_step

- name: 📂 Include assert routines
  include_tasks: "06_assert.yml"
  when: MODE_ASSERT_LOCAL | bool

- name: ♻️ Reset Admin Password
  include_tasks: 07_reset_admin_password.yml
  when: joomla_installed.rc == 0

- name: "📦 Install plg_system_keycloak (native OIDC)"
  include_tasks: 08_oidc_plugin.yml
  when: lookup('config', application_id, 'addons.plg_system_keycloak.enabled') | bool
