---
swarm:
  host: ""
  address: ""
  subnet: ""
  listen_port: 0
  is_hub: false
  public_key: ""
  peers: []
data:
  host: ""
  address: ""
  subnet: ""
  listen_port: 0
  is_hub: false
  public_key: ""
  peers: []
