---
application_id: "web-app-gitea"
entity_name: "{{ application_id | get_entity_name }}"

container_port: "{{ lookup('config', application_id, 'services.gitea.ports.internal.http') }}"

GITEA_LDAP_AUTH_ARGS:
  - '--name "LDAP ({{ DOMAIN_PRIMARY }})"'
  - '--host "{{ LDAP.SERVER.DOMAIN }}"'
  - "--port {{ LDAP.SERVER.PORT }}"
  - '--security-protocol "{{ LDAP.SERVER.SECURITY | trim or "unencrypted" }}"'
  - '--bind-dn "{{ LDAP.DN.ADMINISTRATOR.DATA }}"'
  - '--bind-password "{{ LDAP.BIND_CREDENTIAL }}"'
  - '--user-search-base "{{ LDAP.DN.OU.USERS }}"'
  - '--user-filter "(&(objectClass=inetOrgPerson)(uid=%s))"'
  - '--admin-filter "(memberOf=cn={{ application_id }}-administrator,{{ LDAP.DN.OU.ROLES }})"'
  - '--username-attribute "{{ LDAP.USER.ATTRIBUTES.ID }}"'
  - '--firstname-attribute "{{ LDAP.USER.ATTRIBUTES.FIRSTNAME }}"'
  - '--surname-attribute "{{ LDAP.USER.ATTRIBUTES.SURNAME }}"'
  - '--email-attribute "{{ LDAP.USER.ATTRIBUTES.MAIL }}"'
  - '--public-ssh-key-attribute "{{ LDAP.USER.ATTRIBUTES.SSH_PUBLIC_KEY }}"'
  - "--synchronize-users"
GITEA_CONTAINER: "{{ lookup('config', application_id, 'services.gitea.name') }}"
GITEA_CONTAINER_ADDRESS: "{{ lookup('container_address', application_id, entity_name) }}"
GITEA_USER: "git"
GITEA_CONFIG: "/data/gitea/conf/app.ini"

GITEA_REDIS_ENABLED: "{{ lookup('config', application_id, 'services.redis.enabled') }}"
GITEA_REDIS_ADDRESS: "{{ lookup('engine', 'redis', application_id, 'host') }}:{{ lookup('engine', 'redis', application_id, 'port') }}"
GITEA_REDIS_PASSWORD: "{{ lookup('engine', 'redis', application_id, 'password') }}"

GITEA_OIDC_ENABLED: "{{ lookup('config', application_id, 'services.sso.shared') | bool }}"
GITEA_LDAP_ENABLED: "{{ lookup('config', application_id, 'services.ldap.enabled') }}"
GITEA_IAM_ENABLED: "{{ (GITEA_OIDC_ENABLED | bool) or ( GITEA_LDAP_ENABLED | bool ) }}"
