"""Render the ``infinito`` command tree as a reference page.

The CLI is filesystem-driven: a directory under ``cli/`` holding a
``__main__.py`` is a command. :func:`cli.core.discovery.discover_commands` is
the single source of that rule, so this page asks it rather than walking the
tree again and drifting from the dispatcher.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

from cli.core.discovery import discover_commands

from . import literal

HEADER = """\
CLI Commands
============

Every subcommand of the ``infinito`` entry point, discovered from the ``cli``
package the dispatcher itself reads. The summary is each command module's
docstring; run ``infinito <command> --help`` for its options. Generated by the
documentation build; edit the command module rather than this page.

"""


def summary(main_path: Path) -> str:
    """Return the first line of a command module's docstring.

    The module is parsed rather than imported: importing every command to
    render a page would run each one's import side effects.

    Args:
        main_path: the command's ``__main__.py``.
    """
    try:
        tree = ast.parse(main_path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return "Undocumented."
    doc = ast.get_docstring(tree)
    if not doc:
        return "Undocumented."
    return doc.strip().splitlines()[0].strip()


def generate(cli_dir: Path, output_file: Path) -> int:
    """Write the CLI reference page.

    Args:
        cli_dir: the ``cli`` package directory.
        output_file: the ``.rst`` page to write.

    Returns:
        How many commands the page documents.
    """
    commands = discover_commands(cli_dir)
    entries = [
        f"``infinito {' '.join(command.parts)}``\n   {literal(summary(command.main_path))}"
        for command in commands
    ]
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(HEADER + "\n\n".join(entries) + "\n", encoding="utf-8")
    return len(entries)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate the CLI reference from the cli package."
    )
    parser.add_argument("--cli-dir", required=True, help="Path to the cli package.")
    parser.add_argument("--output-file", required=True, help="Path to the .rst page.")
    args = parser.parse_args(argv)

    output = Path(args.output_file)
    count = generate(Path(args.cli_dir), output)
    print(f"{count} CLI command(s) written to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
