"""Render every documented ``Makefile`` target as a reference page.

The Makefile is the source: a target's documentation is the comment block
directly above it, which ``make help`` already prints. Reading it here instead
of restating it keeps the page from drifting the way a hand-written list does.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from . import literal

TARGET = re.compile(r"^([a-z][a-z0-9-]*):")
COMMENT = re.compile(r"^#\s?(.*)$")
PHONY = re.compile(r"^\.PHONY:")
FIELD = re.compile(r"^(Param|Usage|Example|Note)\s+([^:]+):\s*(.*)$")
SIMPLE_FIELD = re.compile(r"^(Param|Usage|Example|Note):\s*(.*)$")

HEADER = """\
Make Targets
============

Every target of the repository's ``Makefile`` that carries a documentation
comment, with the description and parameters declared beside it. Generated by
the documentation build; edit the ``Makefile`` rather than this page.

"""


def documented_targets(makefile: Path) -> list[tuple[str, list[str]]]:
    """Return every documented target with the comment lines above it.

    Args:
        makefile: the ``Makefile`` to read.

    Returns:
        ``(target, comment lines)`` in file order, targets without a comment
        block included with an empty list.
    """
    found: list[tuple[str, list[str]]] = []
    doc: list[str] = []
    for line in makefile.read_text(encoding="utf-8").splitlines():
        if PHONY.match(line):
            continue
        comment = COMMENT.match(line)
        if comment:
            doc.append(comment.group(1).strip())
            continue
        match = TARGET.match(line)
        if match:
            found.append((match.group(1), doc))
        doc = []
    return found


def _entry(name: str, doc: list[str]) -> str:
    """Return one definition-list entry for a target.

    Args:
        name: the target name.
        doc: the comment lines above it.
    """
    prose = [
        line for line in doc if not FIELD.match(line) and not SIMPLE_FIELD.match(line)
    ]
    fields = []
    for line in doc:
        keyed = FIELD.match(line)
        if keyed:
            fields.append(
                f"   :{keyed.group(1).lower()} {keyed.group(2)}: "
                f"{literal(keyed.group(3))}"
            )
            continue
        plain = SIMPLE_FIELD.match(line)
        if plain:
            fields.append(f"   :{plain.group(1).lower()}: {literal(plain.group(2))}")
    body = literal(" ".join(prose).strip()) or "Undocumented."
    block = [f"``make {name}``", f"   {body}"]
    if fields:
        block.append("")
        block.extend(fields)
    return "\n".join(block)


def generate(makefile: Path, output_file: Path) -> int:
    """Write the make-target reference page.

    Args:
        makefile: the ``Makefile`` to read.
        output_file: the ``.rst`` page to write.

    Returns:
        How many targets the page documents.
    """
    entries = documented_targets(makefile)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(
        HEADER + "\n\n".join(_entry(name, doc) for name, doc in entries) + "\n",
        encoding="utf-8",
    )
    return len(entries)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate the make-target reference from the Makefile."
    )
    parser.add_argument("--makefile", required=True, help="Path to the Makefile.")
    parser.add_argument("--output-file", required=True, help="Path to the .rst page.")
    args = parser.parse_args(argv)

    output = Path(args.output_file)
    count = generate(Path(args.makefile), output)
    print(f"{count} make target(s) written to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
