#!/usr/bin/env python3
"""Generate the operational MCP audit report.

The metadata stays where it belongs: each role owns its ``meta/mcp.yml``, and
nothing here writes back into a role. This script only reads that metadata and
renders the one table a reviewer needs to answer "what does this surface
actually expose, as whom, to whom" without opening twenty-four files.

Run this script from the repository root and commit the result; a lint fails
when the committed report differs from a fresh generation, so the table cannot
drift away from the roles the way the hand-maintained disposition lists once
did.
"""

from pathlib import Path

import yaml

# nocheck: project-root-import — standalone docs generator, no package container to import PROJECT_ROOT from.
REPO_ROOT = Path(__file__).resolve().parents[5]
ROLES_DIR = REPO_ROOT / "roles"
REPORT = Path(__file__).resolve().parent / "mcp-audit.md"

COLUMNS = (
    "role",
    "version",
    "source",
    "transport",
    "auth",
    "subject",
    "scope",
    "tools",
    "implementation",
    "consumers",
    "blocker",
)

EMPTY = "—"


def _load(path):
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def _deployed_version(role_dir):
    """Return the version of the role's own container, or EMPTY."""
    services = _load(role_dir / "meta" / "services.yml")
    entity = role_dir.name.rsplit("-", 1)[-1]
    for name, service in services.items():
        if not isinstance(service, dict):
            continue
        if name == entity and service.get("version"):
            return str(service["version"])
    return EMPTY


def _version(role_dir, mcp):
    """Return the deployed version, naming the verified one when they differ.

    A role that builds from a Dockerfile pins its base image, so the deployed
    version alone would report ``24-bookworm-slim`` for a Flowise surface.
    """
    deployed = _deployed_version(role_dir)
    verified = str(mcp.get("supported_version") or "").strip()
    if verified and verified != deployed:
        return f"{_cell(deployed)} (MCP verified: {_cell(verified)})"
    return _cell(deployed)


def _scope(tools):
    """Return the read/write posture as one token."""
    if not isinstance(tools, dict):
        return EMPTY
    if tools.get("mutating_tools_enabled"):
        return "read-write"
    return "read-only" if tools.get("read_only_default") else EMPTY


def _subject(mcp):
    """Return the declared subject together with the principal it resolves to."""
    subject = str(mcp.get("auth_subject") or "").strip()
    owner = str((mcp.get("credential") or {}).get("owner") or "").strip()
    if subject and owner:
        return f"{subject} (`{owner}`)"
    return subject or owner or EMPTY


def _join(values):
    if not isinstance(values, list) or not values:
        return EMPTY
    return ", ".join(f"`{v}`" for v in values)


def _cell(value):
    text = str(value or "").strip()
    return text.replace("|", r"\|") if text else EMPTY


def rows():
    """Yield one report row per role that owns MCP metadata."""
    for mcp_path in sorted(ROLES_DIR.glob("*/meta/mcp.yml")):
        role_dir = mcp_path.parent.parent
        mcp = _load(mcp_path)
        tools = mcp.get("tools")
        yield {
            "role": f"`{role_dir.name}`",
            "version": _version(role_dir, mcp),
            "source": f"[link]({mcp['source_url']})" if mcp.get("source_url") else EMPTY,
            "transport": _cell(mcp.get("transport")),
            "auth": _cell(mcp.get("auth")),
            "subject": _subject(mcp),
            "scope": _scope(tools),
            "tools": (
                str(len(tools["allowlist"]))
                if isinstance(tools, dict) and isinstance(tools.get("allowlist"), list)
                else EMPTY
            ),
            "implementation": _cell(mcp.get("implementation")),
            "consumers": _join(mcp.get("allowed_consumers")),
            "blocker": _cell(mcp.get("reason")),
        }


def render():
    """Return the full report as markdown."""
    lines = [
        "# 035 - MCP Audit Report",
        "",
        "Generated by [mcp-audit.gen.py](mcp-audit.gen.py); do not edit by hand.",
        "Run that script from the repository root and commit the result.",
        "",
        "One row per role that owns `meta/mcp.yml`. The disposition of every other",
        "role lives in the audit lists of the MCP proxy-expansion requirement.",
        "",
        "`version` is the version the role deploys, read from its own `meta/services.yml`,",
        "not the version the MCP surface was verified against.",
        "`tools` counts the allowlist entries; the names themselves stay in the role.",
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "|" + "|".join(" --- " for _ in COLUMNS) + "|",
    ]
    lines.extend("| " + " | ".join(row[c] for c in COLUMNS) + " |" for row in rows())
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    REPORT.write_text(render(), encoding="utf-8")
    print(f"wrote {REPORT.relative_to(REPO_ROOT)}")
